; Auto-generated. Do not edit!


(cl:in-package jimmy-msg)


;//! \htmlinclude jimmy_servo.msg.html

(cl:defclass <jimmy_servo> (roslisp-msg-protocol:ros-message)
  ((servo_names
    :reader servo_names
    :initarg :servo_names
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element ""))
   (servo_numbers
    :reader servo_numbers
    :initarg :servo_numbers
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (positions
    :reader positions
    :initarg :positions
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass jimmy_servo (<jimmy_servo>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <jimmy_servo>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'jimmy_servo)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name jimmy-msg:<jimmy_servo> is deprecated: use jimmy-msg:jimmy_servo instead.")))

(cl:ensure-generic-function 'servo_names-val :lambda-list '(m))
(cl:defmethod servo_names-val ((m <jimmy_servo>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader jimmy-msg:servo_names-val is deprecated.  Use jimmy-msg:servo_names instead.")
  (servo_names m))

(cl:ensure-generic-function 'servo_numbers-val :lambda-list '(m))
(cl:defmethod servo_numbers-val ((m <jimmy_servo>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader jimmy-msg:servo_numbers-val is deprecated.  Use jimmy-msg:servo_numbers instead.")
  (servo_numbers m))

(cl:ensure-generic-function 'positions-val :lambda-list '(m))
(cl:defmethod positions-val ((m <jimmy_servo>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader jimmy-msg:positions-val is deprecated.  Use jimmy-msg:positions instead.")
  (positions m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<jimmy_servo>)))
    "Constants for message type '<jimmy_servo>"
  '((:ID_R_SHOULDER_PITCH . 16)
    (:ID_L_SHOULDER_PITCH . 12)
    (:ID_R_SHOULDER_ROLL . 17)
    (:ID_L_SHOULDER_ROLL . 13)
    (:ID_R_ELBOW . 19)
    (:ID_L_ELBOW . 15)
    (:ID_R_HIP_YAW . 6)
    (:ID_L_HIP_YAW . 0)
    (:ID_R_HIP_ROLL . 8)
    (:ID_L_HIP_ROLL . 2)
    (:ID_R_HIP_PITCH . 7)
    (:ID_L_HIP_PITCH . 1)
    (:ID_R_KNEE . 9)
    (:ID_L_KNEE . 3)
    (:ID_R_ANKLE_PITCH . 10)
    (:ID_L_ANKLE_PITCH . 4)
    (:ID_R_ANKLE_ROLL . 11)
    (:ID_L_ANKLE_ROLL . 5)
    (:ID_HEAD_PAN . 20)
    (:ID_HEAD_TILT . 21)
    (:ID_R_ELBOW_YAW . 18)
    (:ID_L_ELBOW_YAW . 14)
    (:ID_R_WRIST_YAW . 23)
    (:ID_L_WRIST_YAW . 24)
    (:ID_R_GRIPPER . 25)
    (:ID_L_GRIPPER . 26)
    (:ID_HEAD_TILT_2 . 22)
    (:R_SHOULDER_PITCH . RightShoulderPitch)
    (:L_SHOULDER_PITCH . LeftShoulderPitch)
    (:R_SHOULDER_ROLL . RightShoulderRoll)
    (:L_SHOULDER_ROLL . LeftShoulderRoll)
    (:R_ELBOW . RightElbow)
    (:L_ELBOW . LeftElbow)
    (:R_HIP_YAW . RightHipYaw)
    (:L_HIP_YAW . LeftHipYaw)
    (:R_HIP_ROLL . RightHipRoll)
    (:L_HIP_ROLL . LeftHipRoll)
    (:R_HIP_PITCH . RightHipPitch)
    (:L_HIP_PITCH . LeftHipPitch)
    (:R_KNEE . RightKnee)
    (:L_KNEE . LeftKnee)
    (:R_ANKLE_PITCH . RightAnklePitch)
    (:L_ANKLE_PITCH . LeftAnklePitch)
    (:R_ANKLE_ROLL . RightAnkleRoll)
    (:L_ANKLE_ROLL . LeftAnkleRoll)
    (:HEAD_PAN . HeadPan)
    (:HEAD_TILT . HeadTilt)
    (:R_ELBOW_YAW . RightElbowYaw)
    (:L_ELBOW_YAW . LeftElbowYaw)
    (:R_WRIST_YAW . RightWristYaw)
    (:L_WRIST_YAW . LeftWristYaw)
    (:R_GRIPPER . RightGripper)
    (:L_GRIPPER . LeftGripper)
    (:HEAD_TILT_2 . HeadTilt2))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'jimmy_servo)))
    "Constants for message type 'jimmy_servo"
  '((:ID_R_SHOULDER_PITCH . 16)
    (:ID_L_SHOULDER_PITCH . 12)
    (:ID_R_SHOULDER_ROLL . 17)
    (:ID_L_SHOULDER_ROLL . 13)
    (:ID_R_ELBOW . 19)
    (:ID_L_ELBOW . 15)
    (:ID_R_HIP_YAW . 6)
    (:ID_L_HIP_YAW . 0)
    (:ID_R_HIP_ROLL . 8)
    (:ID_L_HIP_ROLL . 2)
    (:ID_R_HIP_PITCH . 7)
    (:ID_L_HIP_PITCH . 1)
    (:ID_R_KNEE . 9)
    (:ID_L_KNEE . 3)
    (:ID_R_ANKLE_PITCH . 10)
    (:ID_L_ANKLE_PITCH . 4)
    (:ID_R_ANKLE_ROLL . 11)
    (:ID_L_ANKLE_ROLL . 5)
    (:ID_HEAD_PAN . 20)
    (:ID_HEAD_TILT . 21)
    (:ID_R_ELBOW_YAW . 18)
    (:ID_L_ELBOW_YAW . 14)
    (:ID_R_WRIST_YAW . 23)
    (:ID_L_WRIST_YAW . 24)
    (:ID_R_GRIPPER . 25)
    (:ID_L_GRIPPER . 26)
    (:ID_HEAD_TILT_2 . 22)
    (:R_SHOULDER_PITCH . RightShoulderPitch)
    (:L_SHOULDER_PITCH . LeftShoulderPitch)
    (:R_SHOULDER_ROLL . RightShoulderRoll)
    (:L_SHOULDER_ROLL . LeftShoulderRoll)
    (:R_ELBOW . RightElbow)
    (:L_ELBOW . LeftElbow)
    (:R_HIP_YAW . RightHipYaw)
    (:L_HIP_YAW . LeftHipYaw)
    (:R_HIP_ROLL . RightHipRoll)
    (:L_HIP_ROLL . LeftHipRoll)
    (:R_HIP_PITCH . RightHipPitch)
    (:L_HIP_PITCH . LeftHipPitch)
    (:R_KNEE . RightKnee)
    (:L_KNEE . LeftKnee)
    (:R_ANKLE_PITCH . RightAnklePitch)
    (:L_ANKLE_PITCH . LeftAnklePitch)
    (:R_ANKLE_ROLL . RightAnkleRoll)
    (:L_ANKLE_ROLL . LeftAnkleRoll)
    (:HEAD_PAN . HeadPan)
    (:HEAD_TILT . HeadTilt)
    (:R_ELBOW_YAW . RightElbowYaw)
    (:L_ELBOW_YAW . LeftElbowYaw)
    (:R_WRIST_YAW . RightWristYaw)
    (:L_WRIST_YAW . LeftWristYaw)
    (:R_GRIPPER . RightGripper)
    (:L_GRIPPER . LeftGripper)
    (:HEAD_TILT_2 . HeadTilt2))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <jimmy_servo>) ostream)
  "Serializes a message object of type '<jimmy_servo>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'servo_names))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'servo_names))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'servo_numbers))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'servo_numbers))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'positions))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'positions))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <jimmy_servo>) istream)
  "Deserializes a message object of type '<jimmy_servo>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'servo_names) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'servo_names)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'servo_numbers) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'servo_numbers)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'positions) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'positions)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<jimmy_servo>)))
  "Returns string type for a message object of type '<jimmy_servo>"
  "jimmy/jimmy_servo")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'jimmy_servo)))
  "Returns string type for a message object of type 'jimmy_servo"
  "jimmy/jimmy_servo")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<jimmy_servo>)))
  "Returns md5sum for a message object of type '<jimmy_servo>"
  "4ea57b764f702b7be0b6106982510281")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'jimmy_servo)))
  "Returns md5sum for a message object of type 'jimmy_servo"
  "4ea57b764f702b7be0b6106982510281")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<jimmy_servo>)))
  "Returns full string definition for message of type '<jimmy_servo>"
  (cl:format cl:nil "int32 ID_R_SHOULDER_PITCH      = 16~%int32 ID_L_SHOULDER_PITCH      = 12~%int32 ID_R_SHOULDER_ROLL       = 17~%int32 ID_L_SHOULDER_ROLL       = 13~%int32 ID_R_ELBOW               = 19~%int32 ID_L_ELBOW               = 15~%int32 ID_R_HIP_YAW             = 6~%int32 ID_L_HIP_YAW             = 0~%int32 ID_R_HIP_ROLL            = 8~%int32 ID_L_HIP_ROLL            = 2~%int32 ID_R_HIP_PITCH           = 7~%int32 ID_L_HIP_PITCH           = 1~%int32 ID_R_KNEE                = 9~%int32 ID_L_KNEE                = 3~%int32 ID_R_ANKLE_PITCH         = 10~%int32 ID_L_ANKLE_PITCH         = 4~%int32 ID_R_ANKLE_ROLL          = 11~%int32 ID_L_ANKLE_ROLL          = 5~%int32 ID_HEAD_PAN              = 20~%int32 ID_HEAD_TILT             = 21~%int32 ID_R_ELBOW_YAW           = 18~%int32 ID_L_ELBOW_YAW           = 14~%int32 ID_R_WRIST_YAW           = 23~%int32 ID_L_WRIST_YAW           = 24~%int32 ID_R_GRIPPER             = 25~%int32 ID_L_GRIPPER             = 26~%int32 ID_HEAD_TILT_2           = 22~%~%string R_SHOULDER_PITCH      = RightShoulderPitch~%string L_SHOULDER_PITCH      = LeftShoulderPitch~%string R_SHOULDER_ROLL       = RightShoulderRoll~%string L_SHOULDER_ROLL       = LeftShoulderRoll~%string R_ELBOW               = RightElbow~%string L_ELBOW               = LeftElbow~%string R_HIP_YAW             = RightHipYaw~%string L_HIP_YAW             = LeftHipYaw~%string R_HIP_ROLL            = RightHipRoll~%string L_HIP_ROLL            = LeftHipRoll~%string R_HIP_PITCH           = RightHipPitch~%string L_HIP_PITCH           = LeftHipPitch~%string R_KNEE                = RightKnee~%string L_KNEE                = LeftKnee~%string R_ANKLE_PITCH         = RightAnklePitch~%string L_ANKLE_PITCH         = LeftAnklePitch~%string R_ANKLE_ROLL          = RightAnkleRoll~%string L_ANKLE_ROLL          = LeftAnkleRoll~%string HEAD_PAN              = HeadPan~%string HEAD_TILT             = HeadTilt~%string R_ELBOW_YAW           = RightElbowYaw~%string L_ELBOW_YAW           = LeftElbowYaw~%string R_WRIST_YAW           = RightWristYaw~%string L_WRIST_YAW           = LeftWristYaw~%string R_GRIPPER             = RightGripper~%string L_GRIPPER             = LeftGripper~%string HEAD_TILT_2           = HeadTilt2~%~%string[] servo_names~%int32[] servo_numbers~%float64[] positions~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'jimmy_servo)))
  "Returns full string definition for message of type 'jimmy_servo"
  (cl:format cl:nil "int32 ID_R_SHOULDER_PITCH      = 16~%int32 ID_L_SHOULDER_PITCH      = 12~%int32 ID_R_SHOULDER_ROLL       = 17~%int32 ID_L_SHOULDER_ROLL       = 13~%int32 ID_R_ELBOW               = 19~%int32 ID_L_ELBOW               = 15~%int32 ID_R_HIP_YAW             = 6~%int32 ID_L_HIP_YAW             = 0~%int32 ID_R_HIP_ROLL            = 8~%int32 ID_L_HIP_ROLL            = 2~%int32 ID_R_HIP_PITCH           = 7~%int32 ID_L_HIP_PITCH           = 1~%int32 ID_R_KNEE                = 9~%int32 ID_L_KNEE                = 3~%int32 ID_R_ANKLE_PITCH         = 10~%int32 ID_L_ANKLE_PITCH         = 4~%int32 ID_R_ANKLE_ROLL          = 11~%int32 ID_L_ANKLE_ROLL          = 5~%int32 ID_HEAD_PAN              = 20~%int32 ID_HEAD_TILT             = 21~%int32 ID_R_ELBOW_YAW           = 18~%int32 ID_L_ELBOW_YAW           = 14~%int32 ID_R_WRIST_YAW           = 23~%int32 ID_L_WRIST_YAW           = 24~%int32 ID_R_GRIPPER             = 25~%int32 ID_L_GRIPPER             = 26~%int32 ID_HEAD_TILT_2           = 22~%~%string R_SHOULDER_PITCH      = RightShoulderPitch~%string L_SHOULDER_PITCH      = LeftShoulderPitch~%string R_SHOULDER_ROLL       = RightShoulderRoll~%string L_SHOULDER_ROLL       = LeftShoulderRoll~%string R_ELBOW               = RightElbow~%string L_ELBOW               = LeftElbow~%string R_HIP_YAW             = RightHipYaw~%string L_HIP_YAW             = LeftHipYaw~%string R_HIP_ROLL            = RightHipRoll~%string L_HIP_ROLL            = LeftHipRoll~%string R_HIP_PITCH           = RightHipPitch~%string L_HIP_PITCH           = LeftHipPitch~%string R_KNEE                = RightKnee~%string L_KNEE                = LeftKnee~%string R_ANKLE_PITCH         = RightAnklePitch~%string L_ANKLE_PITCH         = LeftAnklePitch~%string R_ANKLE_ROLL          = RightAnkleRoll~%string L_ANKLE_ROLL          = LeftAnkleRoll~%string HEAD_PAN              = HeadPan~%string HEAD_TILT             = HeadTilt~%string R_ELBOW_YAW           = RightElbowYaw~%string L_ELBOW_YAW           = LeftElbowYaw~%string R_WRIST_YAW           = RightWristYaw~%string L_WRIST_YAW           = LeftWristYaw~%string R_GRIPPER             = RightGripper~%string L_GRIPPER             = LeftGripper~%string HEAD_TILT_2           = HeadTilt2~%~%string[] servo_names~%int32[] servo_numbers~%float64[] positions~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <jimmy_servo>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'servo_names) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'servo_numbers) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'positions) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <jimmy_servo>))
  "Converts a ROS message object to a list"
  (cl:list 'jimmy_servo
    (cl:cons ':servo_names (servo_names msg))
    (cl:cons ':servo_numbers (servo_numbers msg))
    (cl:cons ':positions (positions msg))
))
