/* Auto-generated by genmsg_cpp for file /home/sophie/catkin_ws/src/jimmy/msg/jimmy_command.msg */
#ifndef JIMMY_MESSAGE_JIMMY_COMMAND_H
#define JIMMY_MESSAGE_JIMMY_COMMAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace jimmy
{
template <class ContainerAllocator>
struct jimmy_command_ {
  typedef jimmy_command_<ContainerAllocator> Type;

  jimmy_command_()
  : header()
  , cmd(0)
  , param()
  {
  }

  jimmy_command_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , cmd(0)
  , param(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _cmd_type;
  int32_t cmd;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _param_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  param;

  enum { CMD_NECK = -2 };
  enum { CMD_SAVE_AND_QUIT = -1 };
  enum { CMD_IDLE = 0 };
  enum { CMD_WALK = 1 };
  enum { CMD_GESTURE_START = 2 };

  typedef boost::shared_ptr< ::jimmy::jimmy_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jimmy::jimmy_command_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct jimmy_command
typedef  ::jimmy::jimmy_command_<std::allocator<void> > jimmy_command;

typedef boost::shared_ptr< ::jimmy::jimmy_command> jimmy_commandPtr;
typedef boost::shared_ptr< ::jimmy::jimmy_command const> jimmy_commandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::jimmy::jimmy_command_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::jimmy::jimmy_command_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace jimmy

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::jimmy::jimmy_command_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::jimmy::jimmy_command_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::jimmy::jimmy_command_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2a88fad4ecf04f86731a30af3dfd54d2";
  }

  static const char* value(const  ::jimmy::jimmy_command_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2a88fad4ecf04f86ULL;
  static const uint64_t static_value2 = 0x731a30af3dfd54d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::jimmy::jimmy_command_<ContainerAllocator> > {
  static const char* value() 
  {
    return "jimmy/jimmy_command";
  }

  static const char* value(const  ::jimmy::jimmy_command_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::jimmy::jimmy_command_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
int32 CMD_NECK                = -2\n\
int32 CMD_SAVE_AND_QUIT       = -1\n\
int32 CMD_IDLE                = 0\n\
int32 CMD_WALK                = 1\n\
int32 CMD_GESTURE_START       = 2\n\
# 3 and higher are gestures\n\
\n\
int32 cmd\n\
float64[] param  \n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::jimmy::jimmy_command_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::jimmy::jimmy_command_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::jimmy::jimmy_command_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::jimmy::jimmy_command_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.cmd);
    stream.next(m.param);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct jimmy_command_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jimmy::jimmy_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::jimmy::jimmy_command_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cmd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cmd);
    s << indent << "param[]" << std::endl;
    for (size_t i = 0; i < v.param.size(); ++i)
    {
      s << indent << "  param[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.param[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // JIMMY_MESSAGE_JIMMY_COMMAND_H

