/* Auto-generated by genmsg_cpp for file /home/sophie/catkin_ws/src/jimmy/msg/jimmy_setJoints.msg */
#ifndef JIMMY_MESSAGE_JIMMY_SETJOINTS_H
#define JIMMY_MESSAGE_JIMMY_SETJOINTS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace jimmy
{
template <class ContainerAllocator>
struct jimmy_setJoints_ {
  typedef jimmy_setJoints_<ContainerAllocator> Type;

  jimmy_setJoints_()
  : positions()
  {
  }

  jimmy_setJoints_(const ContainerAllocator& _alloc)
  : positions(_alloc)
  {
  }

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _positions_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  positions;


  typedef boost::shared_ptr< ::jimmy::jimmy_setJoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jimmy::jimmy_setJoints_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct jimmy_setJoints
typedef  ::jimmy::jimmy_setJoints_<std::allocator<void> > jimmy_setJoints;

typedef boost::shared_ptr< ::jimmy::jimmy_setJoints> jimmy_setJointsPtr;
typedef boost::shared_ptr< ::jimmy::jimmy_setJoints const> jimmy_setJointsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::jimmy::jimmy_setJoints_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::jimmy::jimmy_setJoints_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace jimmy

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::jimmy::jimmy_setJoints_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::jimmy::jimmy_setJoints_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::jimmy::jimmy_setJoints_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3b33cf2d1f9005e741ee291d519b97ee";
  }

  static const char* value(const  ::jimmy::jimmy_setJoints_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3b33cf2d1f9005e7ULL;
  static const uint64_t static_value2 = 0x41ee291d519b97eeULL;
};

template<class ContainerAllocator>
struct DataType< ::jimmy::jimmy_setJoints_<ContainerAllocator> > {
  static const char* value() 
  {
    return "jimmy/jimmy_setJoints";
  }

  static const char* value(const  ::jimmy::jimmy_setJoints_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::jimmy::jimmy_setJoints_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64[] positions\n\
";
  }

  static const char* value(const  ::jimmy::jimmy_setJoints_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::jimmy::jimmy_setJoints_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.positions);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct jimmy_setJoints_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jimmy::jimmy_setJoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::jimmy::jimmy_setJoints_<ContainerAllocator> & v) 
  {
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.positions[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // JIMMY_MESSAGE_JIMMY_SETJOINTS_H

